### ISSUE TITLE
Question regarding the bilevel penalty optimizer

### ISSUE THREAD

**Issue by pipilurj** [jihunhamm/bilevel-penalty#4]
Hi, very interesting work! I have a few questions and hope that you can help me. 
I noticed in bilevel-penalty/bilevel_penalty_aug_lag_synthetic.py, line 62 and 63, there seem to be separate objectives for upper and lower problems, .i.e, h_upper and h_lower, what is the term lamb_g present only in lower level objective? 
Another question is also in the same file, line 79-83. there's a definition of single level update, but I didn't see it being used anywhere, was it just a trial? or is it somehow useful?
Thank you very much!

**Comment by akshaymehra24** [comment]
Hi @pipilurj 

The lamb_g term is a regularization term added only to the update of the lower-level variable since the minimization of the term ||\nabla_v g|| could lead to a maxima for the function g instead of a minima. You can see the discussion on this in the "improvements" section on page 7 and in Appendix C of the paper. 

Line 79-83 were for some testing and can be ignored. 

Let me know if you have any other questions.
